### ISSUE TITLE
Why use Double.*_INFINITY instead of Integer.*_VALUE?

### ISSUE THREAD

**Issue by EmmanuelMess** [LazoCoder/Tic-Tac-Toe#1]
Why not Integer.MIN_VALUE here?:
https://github.com/LazoCoder/Tic-Tac-Toe/blob/1ac2fca01ab33d10c3299efcf25e10c14a8f08c3/TicTacToe/ArtificialIntelligence/MiniMax.java#L60

**Comment by LazoVelko** [comment]
Either way works in this context since its just a little tic tac toe program and we know that *score* will never be less than -2^31.

https://github.com/LazoCoder/Tic-Tac-Toe/blob/1ac2fca01ab33d10c3299efcf25e10c14a8f08c3/TicTacToe/ArtificialIntelligence/MiniMax.java#L68

But using Double.NEGATIVE_INFINITY might be better practice for larger programs. What if somebody changes *score* from int to long and also changes the scoring values:

https://github.com/LazoCoder/Tic-Tac-Toe/blob/1ac2fca01ab33d10c3299efcf25e10c14a8f08c3/TicTacToe/ArtificialIntelligence/MiniMax.java#L126

There is a chance of returning a value to *score* that is less than Integer.MIN_VALUE and this might break the algorithm:

https://github.com/LazoCoder/Tic-Tac-Toe/blob/1ac2fca01ab33d10c3299efcf25e10c14a8f08c3/TicTacToe/ArtificialIntelligence/MiniMax.java#L70
